#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fail
set -o errexit
MAUTIC_VERSION="4.4.1"
DESTDIR="/var/www/htdocs/mautic"

echo "* Install mautic"
mkdir -p "${DESTDIR}/releases/mautic-${MAUTIC_VERSION}"
cd "${DESTDIR}/releases/mautic-${MAUTIC_VERSION}"
curl -s -L -O https://download.qutic.com/src/mautic/${MAUTIC_VERSION}.zip
unzip ${MAUTIC_VERSION}.zip
rm ${MAUTIC_VERSION}.zip
cd $DESTDIR
ln -nfs $DESTDIR/releases/mautic-${MAUTIC_VERSION} current
cp /var/www/htdocs/mautic/current/app/bundles/CoreBundle/Templating/Helper/GravatarHelper.php \
  /var/www/htdocs/mautic/current/app/bundles/CoreBundle/Templating/Helper/GravatarHelper.php.bak
chown -R www:www "$DESTDIR"

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

echo "* Add commands to bash-history";
cat > /root/.bash_history << EOF
su - www
tail -f /var/log/php-fpm.log
tail -f /var/log/nginx/access.log
svcadm restart php-fpm ; svcadm restart nginx
svcadm restart php-fpm
svcadm restart nginx
svcs -vx
EOF
chmod 0600 /root/.bash_history

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
